[package]
name = "rtnetlink-static-ip"
version = "0.1.0"
edition = "2021"

[dependencies]
rtnetlink = "*"
tokio = { version = "*", features = ["full"] }
anyhow = "*"
futures = "*"
ipnetwork = "*"

[lib]
name = "lib"
path = "src/lib.rs"

